const mongoose = require('mongoose');
const ticketSchema = new mongoose.Schema({
    title: {type: String, required: true},
    description: {type: String},
    createdBy: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
    status: {type: String, enum: ['todo', 'in_progress', 'done', 'closed'], default: 'closed'},
    priority: {type: String, enum: ['critical', 'high', 'medium', 'low'], default: 'low'},
    estHours: {type: Number},
    assigneeId: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
    // labels: [{
    //     type: mongoose.Schema.Types.ObjectId,
    //     ref: 'Label'
    // }
    // ]
    source: {type: String},
    autoGenerated:{type: Boolean, default: false},
    deadline: {type: Date, required: true},
    aiTriageId: {type: mongoose.Schema.Types.ObjectId, ref: 'TriageJobAI'},

}, {
    timestamps: true
})

const Ticket = mongoose.model('Ticket', ticketSchema)
module.exports = Ticket